在TensorFlow中，使用张量表示数据，用计算图搭建神经网络，用会话执行计算图，优化线上的权重（参数），得到模型。

## 张量 ##

张量就是多维数组，用阶表示张量的维度。

0阶张量： **标量**，例如123

1阶张量： **向量**，例如[1,2,3]

2阶张量： **矩阵**，例如[[1,2,3],[4,5,6],[7,8,9]]

n阶张量： **n阶数组**，张量右边有n个方括号[[[[[……(**n个[**)

## 数据类型 ##

TensorFlow的数据类型有：tf.float32、tf.int32等。


In [3]:
import tensorflow as tf

#定义一个张量等于[1.0, 2.0]
a=tf.constant([1.0, 2.0])
#定义一个张量等于[3.0, 4.0]
b=tf.constant([3.0, 4.0])
#实现a+b的加法
result=a+b
#打印结果
print(result)


tf.Tensor([4. 6.], shape=(2,), dtype=float32)


输出结果： shape=(2,)表示一维数组长度为2，dtype=float32表示数据类型为浮点型。

## 计算图 ##

搭建神经网络的计算过程，承载一个或多个计算节点的一张图，只搭建网络，不运算。

神经网络的基本模型是神经元，神经元的基本模型其实就是数学中的乘、加运算。

下面用x1、x2表示输入，w1、w2表示x1到y和x2到y的权重，y=x1* w1+x2* w2

In [7]:
x=tf.constant([[1.0, 2.0]])
w=tf.constant([[3.0], [4.0]])
y=tf.matmul(x,w)
print(y)

tf.Tensor([[11.]], shape=(1, 1), dtype=float32)


这里的输出为：tf.Tensor([[11.]], shape=(1, 1), dtype=float32)，表示y是一个张量，只搭建承载计算过程的计算图，并没有运算，如果我们想得到运算结果就要用到会话Session()。

## 会话（Session）##

执行计算图中的节点运算。

我们用with结构实现，语法如下：

``` python
with tf.Session() as sess:
    print(sess.run(y))
```

In [15]:
#接上面的计算图y，使用Session执行。
tf.compat.v1.disable_eager_execution()
x=tf.constant([[1.0, 2.0]])
w=tf.constant([[3.0], [4.0]])
y=tf.matmul(x,w)
with tf.compat.v1.Session() as sess:
    print(sess.run(y))

[[11.]]


In [ ]:
运行Session()后打印出执行结果为11。